- name: Check if nifi is present in destination
  stat: path={{ base_dir }}/cqube/nifi
  register: status
  tags: update

- name: stop nifi if its running
  shell: "{{ base_dir }}/cqube/nifi/bin/nifi.sh stop"
  when: status.stat.exists == true
  tags: update

- name: Delete existing templates in nifi
  become: yes
  file:
    path: "{{ base_dir }}/cqube/nifi/conf/flow.xml.gz"
    state: absent
  tags: update

- name: Creates a directory
  file: path={{ base_dir }}/cqube/temp_nifi state=directory
  tags: update

- name: Move nifi folder to a temp folder
  become: yes
  command: mv {{ base_dir }}/cqube/nifi {{ base_dir }}/cqube/temp_nifi
  tags: update

- name: Rename the temp_nifi folder
  become: yes
  command: mv {{ base_dir }}/cqube/temp_nifi {{ base_dir }}/cqube/nifi
  tags: update

- name: Move Queries folder outsside of nifi
  become: yes
  command: mv {{ base_dir }}/cqube/nifi_queries {{ base_dir }}/cqube/nifi
  tags: update
