---
- name: Stoping the admin_client_side app
  become: yes
  shell: pm2 stop admin_client_side
  tags: update

- name: Delete admin_client_side directory
  file:
    path: "{{ base_dir }}/cqube/admin_dashboard/client_side"
    state: absent
  tags: update

- name: Making sure {{ base_dir }}/cqube/admin_dashboard/client_side directory is present
  file:
    path: "{{ base_dir }}/cqube/admin_dashboard/client_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [ install, update ]

- name: copying server-side script
  shell: "cp -R ../../development/admin/client-side/* {{base_dir}}/cqube/admin_dashboard/client_side"
  tags: [ install, update ]

- name: Configure the environment.ts
  template:
    src: environment.ts.j2
    dest: "{{ base_dir }}/cqube/admin_dashboard/client_side/src/environments/environment.ts"
  tags: [ install, update ]

- name: Configure the environment.prod.ts
  template:
    src: environment.prod.ts.j2
    dest: "{{ base_dir }}/cqube/admin_dashboard/client_side/src/environments/environment.prod.ts"
  tags: [ install, update ]   

- name: Install Angular packages based on package.json.
  npm:
    path: "{{ base_dir }}/cqube/admin_dashboard/client_side"
  tags: [ install, update ]

- name: Building Angular client-side code
  command: ng build --prod
  args:
    chdir: "{{ base_dir }}/cqube/admin_dashboard/client_side"
  tags: [ install, update ]

- name: changing ownership
  file:
    path: "{{ base_dir }}/cqube/admin_dashboard/client_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
  tags: [ install, update ]