---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Installing jdk
      apt: name=openjdk-8-jdk

    - name: Java | Define variable environment
      action: shell sudo bash -c 'echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc'
    - name: Java
      action: shell sudo bash -c 'echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> ~/.bashrc'

