---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Installing python3
      apt: name=python3
    - name: Installing pip
      apt: name=python3-pip
    - name: Installing pip3
      apt: name=python-pip
    - pip:
        name: boto3
        # executable: pip3

