- set_fact:
     temp_parameter: "{{ temp.parameter }}"

- debug:
     var: temp_parameter

- name: Get parameter contexts
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/parameter-contexts
    method: GET
  register: parameters

- name: Delete parameter context
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/parameter-contexts/{{ item.id }}?version={{ item.revision.version }}&disconnectedNodeAcknowledged=false
    method: DELETE
  loop: "{{ parameters.json | json_query('parameterContexts[*]') }}"
  when: item.component.name == temp_parameter 
  no_log: True
