- name: gunicorn systemd setup
  template:
    owner: root
    group: root
    mode: 0644
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  tags: install

- name: reload systemd
  shell: sudo systemctl daemon-reload
  tags: install

- name: Starting the emission_app service
  service: 
    name: gunicorn
    enabled: yes
    state: started
  tags: [ install, update ]
