{
 "title": "cQube Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization ( in percentage % )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage ( in percentage % )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))"
    }
   ]
  },
  {
   "title": "Server Storage - current  ( in percentage % ) ",
   "type": "graph",
   "description": "Storage used in percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /  node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Nifi Jvm heap memory used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nifi_jvm_heap_used", "legendFormat": "JVM heap used" }
   ]
  },
  {
   "title": "Nifi - Jvm heap usage ( in percentage %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "nifi_jvm_heap_usage", "legendFormat": "Nifi Jvm heap usage" }
   ]
  },
  {
   "title": "Total Files metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nifi_processor_counters{counter_name=\"total_input_file_count\"})",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(nifi_processor_counters{counter_name=\"total_processed_file_count\"})",
     "legendFormat": "processed "
    }
   ]
  },
  {
   "title": "Total Records metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nifi_processor_counters{counter_name=\"total_input_file_record_count\"})",
     "legendFormat": "Input "
    },
    {
     "expr": "sum(nifi_processor_counters{counter_name=\"total_processed_record_count\"})",
     "legendFormat": "Processed "
    }
   ]
  }
 ]
}