---

- name: Ensure Kong DB database
  postgresql_db:
    name: "{{ sansible_kong_db_name}}"
    state: present
    login_host: "{{ sansible_kong_db_host }}"
    login_user: "{{ sansible_kong_db_root_user }}"
    login_password: "{{ sansible_kong_db_root_password }}"
  register: create_db
  when:
    - sansible_kong_db_root_user is not none
    - sansible_kong_db_root_password is not none

- name: Ensure Kong DB user
  postgresql_user:
    db: "{{ sansible_kong_db_name }}"
    login_host: "{{ sansible_kong_db_host }}"
    login_password: "{{ sansible_kong_db_root_password }}"
    login_user: "{{ sansible_kong_db_root_user }}"
    name: "{{ sansible_kong_db_user }}"
    password: "{{ sansible_kong_db_password }}"
    priv: "ALL"
    state: present
  when:
    - sansible_kong_db_root_user is not none
    - sansible_kong_db_root_password is not none
    - create_db.changed

- name: Write kong nginx config
  become: yes
  template:
    dest: /etc/kong/default_nginx.template
    group: root
    mode: 0644
    owner: root
    src: default_nginx.template.j2
  notify:
    - restart kong

- name: Write kong config
  become: yes
  template:
    dest: /etc/kong/kong.conf
    group: root
    mode: 0644
    owner: root
    src: kong.conf.j2
  notify:
    - restart kong

- name: Flush handlers to ensure everything is up to date
  meta: flush_handlers

- name: Ensure Kong is running
  become: yes
  service:
    name: kong
    state: started
