- name: Fetch nifi root processor group id
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/root
    method: GET
  register: processor_id

- name: upload template
  action: shell curl -POST http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ processor_id.json.id }}/templates/upload -k -v -F template=@../../development/nifi/semester_transformer.xml
  register: xml_output
  args:
    warn: false

- name: upload parameters
  action: shell curl -d @{{ item }} -H Content-Type:application/json -X POST http://localhost:{{ nifi_port }}/nifi-api/parameter-contexts
  with_items:
     - nifi_json_files/raw.json
     - nifi_json_files/assessment.json
  args:
    warn: false

- name: Get processor group
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ processor_id.json.id }}
    method: GET
  register: processor_group

- name: Get template list
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/templates
    method: GET
  register: template_list

- name: Instatiate template list
  action: shell curl -X POST  -H 'Content-Type:application/json' -d '{ "originX":0.0, "originY":0.0, "templateId":"{{ item.template.id }}" }' http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ processor_group.json.processGroupFlow.id }}/template-instance
  loop: "{{ template_list.json | json_query('templates[*]') }}"
  when: item.template.name == 'semester_transformer'
  no_log: True
  args:
    warn: false

- name: Fetch nifi processor group id
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/root
    method: GET
  register: processor_id

- name: Get processor group after instantiation of template
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ processor_id.json.id }}
    method: GET
  register: processor_group_temp

#--- Fetching processor group id of semester processor ---
- name: Get processor group id of the semester processor
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ item.id }}
    method: GET
  loop: "{{ processor_group_temp.json | json_query('processGroupFlow.flow.processGroups[*]') }}"
  when: item.component.name == 'semester_transformer'
  register: processor_group_template
  no_log: True

- set_fact:
    semester_pg_id: "{{  processor_group_template | json_query('results[?item.component.name == `semester_transformer`]') }}"

- name: Get multi processor group
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ semester_pg_id[0].item.component.id }}
    method: GET
  register: multi_processor

- name: Run jmesquery
  debug: msg={{ multi_processor.json | json_query(jmesquery) }}
  vars:
    jmesquery: "processGroupFlow.flow.processGroups[*].{Name: component.name, ID: component.id,  Version: revision.version}"
  register: output

#--- Display ID and Version of respective processor groups ---
- name: Display ID of semester raw processor
  debug:
    var: item
  loop: "{{ output | json_query(semester_raw_id) }}"
  vars:
    semester_raw_id: "msg[?Name=='cQube_raw_data_fetch_sem'].ID"
  register: semester_raw_id

- name: Display version of semester raw processor
  debug:
    var: item
  loop: "{{ output | json_query(semester_raw_version) }}"
  vars:
    semester_raw_version: "msg[?Name=='cQube_raw_data_fetch_sem'].Version"
  register: semester_raw_version

- name: Display ID of assessment processor
  debug:
    var: item
  loop: "{{ output | json_query(assessment_id) }}"
  vars:
    assessment_id: "msg[?Name=='student_assessment_processor'].ID"
  register: assessment_id

- name: Display version of assessment processor
  debug:
    var: item
  loop: "{{ output | json_query(assessment_version) }}"
  vars:
    assessment_version: "msg[?Name=='student_assessment_processor'].Version"
  register: assessment_version

- name: Get parameter contexts
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/parameter-contexts
    method: GET
  register: parameters

#--- Connection of processor groups to respective parameter contexts ---
- name: Connection semester raw processor group to raw parameters
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ semester_raw_id.results[0].item }}
    method: PUT
    body_format: json
    body: {"revision": {
            "version": "{{ semester_raw_version.results[0].item }}",
            "lastModifier": "Ansible"
        },"component":
              {"id": "{{ semester_raw_id.results[0].item }}","parameterContext":{"id": "{{ item.component.id }}"}}
     }
  loop: "{{ parameters.json | json_query('parameterContexts[*]') }}"
  when: item.component.name == 'cQube-raw-data-fetch-parameters'
  no_log: True

- name: Connection assessment processor group to assessment parameters
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ assessment_id.results[0].item }}
    method: PUT
    body_format: json
    body: {"revision": {
            "version": "{{ assessment_version.results[0].item }}",
            "lastModifier": "Ansible"
        },"component":
              {"id": "{{ assessment_id.results[0].item }}","parameterContext":{"id": "{{ item.component.id }}"}}
     }
  loop: "{{ parameters.json | json_query('parameterContexts[*]') }}"
  when: item.component.name == 'student_assessment_parameters'
  no_log: True

- name: Create DistributedMapCacheServer
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/process-groups/{{ semester_raw_id.results[0].item }}/controller-services
    method: POST
    body_format: json
    status_code: 201
    body: {"revision": {"clientId": "ansible","version": 0,"lastModifier": "ansible"},"component":{"type":"org.apache.nifi.distributed.cache.server.map.DistributedMapCacheServer","properties" : { "Port": "4558"}}}

#--- Run a python code to load required parameter values ---
- name: Deleting params file if exists
  file:
    path: "{{ base_dir }}/cqube/emission_app/python/update_nifi_params.py"
    state: absent

- name: creating python code for parameters
  template:
    src: update_nifi_params.py.j2
    dest: "{{ base_dir }}/cqube/emission_app/python/update_nifi_params.py"
    mode: "0644"

- name: Run python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/update_nifi_params.py"

#--- Starting of Controllers ---
- name: Get controllers
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ semester_raw_id.results[0].item }}/controller-services
    method: GET
  register: controllers_list_raw
  no_log: True

- name: Get controllers
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ assessment_id.results[0].item }}/controller-services
    method: GET
  register: controllers_list_assessment
  no_log: True

- name: Add s3 credentials parameters
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}
    method: PUT
    body_format: json
    body: {"revision": {
             "version": "{{ item.revision.version }}",
            "lastModifier": "Ansible"
        },
        "component": {"id": "{{ item.id }}", "name": "cQube_s3_sem_raw",
        "properties" : { "Access Key" : "#{s3_access_key}", "Secret Key":"#{s3_secret_key}"}}

     }
  loop: "{{ controllers_list_raw.json | json_query('controllerServices[*]') }}"
  when: item.component.name == 'cQube_s3_sem_raw'
  no_log: True

- name: Add s3 credentials parameters
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}
    method: PUT
    body_format: json
    body: {"revision": {
             "version": "{{ item.revision.version }}",
            "lastModifier": "Ansible"
        },
        "component": {"id": "{{ item.id }}", "name": "cQube_s3_sem",
        "properties" : { "Access Key" : "#{s3_access_key}", "Secret Key":"#{s3_secret_key}"}}

     }
  loop: "{{ controllers_list_assessment.json | json_query('controllerServices[*]') }}"
  when: item.component.name == 'cQube_s3_sem'
  no_log: True
  
- name: Add postgre-source-pwd
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}
    method: PUT
    body_format: json
    body: {"revision": {
             "version": "{{ item.revision.version }}",
            "lastModifier": "Ansible"
        },
        "component": {"id": "{{ item.id }}", "name": "postgres_sem_raw",
        "properties" : { "Password" : "#{db_password}"}}

     }
  loop: "{{ controllers_list_raw.json | json_query('controllerServices[*]') }}"
  when: item.component.name == 'postgres_sem_raw'
  no_log: True

- name: Add postgre-source-pwd
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}
    method: PUT
    body_format: json
    body: {"revision": {
             "version": "{{ item.revision.version }}",
            "lastModifier": "Ansible"
        },
        "component": {"id": "{{ item.id }}", "name": "postgres_sem",
        "properties" : { "Password" : "#{db_password}"}}

     }
  loop: "{{ controllers_list_assessment.json | json_query('controllerServices[*]') }}"
  when: item.component.name == 'postgres_sem'
  no_log: True

- name: Get controllers raw updated
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ semester_raw_id.results[0].item }}/controller-services
    method: GET
  register: controllers_list_raw_updated
  no_log: True

- name: Get controllers assessment updated
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/flow/process-groups/{{ assessment_id.results[0].item }}/controller-services
    method: GET
  register: controllers_list_assessment_updated
  no_log: True
  
- name: Start semester raw controllers
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}/run-status
    method: PUT
    body_format: json
    body: {"revision": {
            "version": "{{ item.revision.version }}"
        },
        "state":"ENABLED"
        }
  loop: "{{ controllers_list_raw_updated.json | json_query('controllerServices[*]') }}"
  when: item.component.state == 'DISABLED'
  no_log: True

- name: Start assessment controllers
  uri:
    url: http://localhost:{{ nifi_port }}/nifi-api/controller-services/{{ item.id }}/run-status
    method: PUT
    body_format: json
    body: {"revision": {
            "version": "{{ item.revision.version }}"
        },
        "state":"ENABLED"
        }
  loop: "{{ controllers_list_assessment_updated.json | json_query('controllerServices[*]') }}"
  when: item.component.state == 'DISABLED'
  no_log: True

