/*Truncating aggregation tables and static tables*/

truncate only crc_visits_frequency,diksha_total_content,diksha_tpd_agg,periodic_exam_school_qst_result,periodic_exam_school_result,
		school_invalid_data,school_student_subject_total_marks,school_student_total_attendance,udise_school_metrics_agg,
		udise_school_metrics_temp,school_infrastructure_score,block_tmp,cluster_tmp,district_tmp,school_tmp,block_mst,
		cluster_mst,district_mst,school_master,school_hierarchy_details,school_geo_master,student_attendance_meta;
