---
- name: Installing cQube
  hosts: prodserver
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config.yml
    - ../memory_config.yml
    - ../.version

  roles:
          - backup 

