---
- name: Installing cQube
  hosts: "{{my_hosts}}"
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config.yml
    - ../migrate_config.yml
  roles:
          - get_remote_ip
