---
- name: Installing cQube
  hosts: "{{ my_hosts }}"
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config.yml
    - ../migrate_config.yml
    - ../memory_config.yml
    - ../.version

  roles:
          - { role: java, tags: install }  
          - { role: python, tags: install }
          - createdb
          - python_flask
          - { role: kong, tags: install }
          - keycloak
          - prometheus
          - { role: grafana, tags: install }

          - nifi_install   
          - angular
          - cqube_version
