---
- name: Remove cQube and postgres if its installed in remote machine
  hosts: "{{my_hosts}}"
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config.yml
    - ../migrate_config.yml
    - ../.version

  roles:
          - remote_sanity
