- name: Copy postgres backup to remote machine
  copy: src=/home/{{system_user_name}}/bk_db_name.tar dest=/tmp/bk_db_name.tar
  tags: install

- name: Restore postgres backup to remote machine
  shell: PGPASSWORD="{{db_password}}" pg_restore --host localhost --port 5432 --username {{remote_db_user}} --dbname {{remote_db_name}} --verbose "/tmp/bk_db_name.tar" -c --if-exists
  tags: install


- name: copying output files backup to remote machine
  copy: src={{source_output_directory}} dest={{output_directory}}
  when: storage_type == "local" and remote_storage_type == "local"
  tags: install

- name: copying aws_s3_config.yml to remote host
  copy: src=../../../../aws_s3_config.yml dest=/home/{{remote_system_user_name}}/aws_s3_config.yml
  when: storage_type == "s3"
  tags: install

- name: copying local_storage_config.yml to remote host
  copy: src=../../../../local_storage_config.yml dest=/home/{{remote_system_user_name}}/local_storage_config.yml
  when: storage_type == "local"
  tags: install

- name: copying the data migration script to remote host
  copy: src=../../../../data_mig.sh dest=/home/{{remote_system_user_name}}/data_mig.sh
  tags: install

- name: Running the data migration script
  command: bash /home/{{remote_system_user_name}}/data_mig.sh
  tags: install
