---
#Constant Parameters ( PLEASE DO NOT CHANGE )
db_driver_class_name: org.postgresql.Driver
db_connection_url: jdbc:postgresql://localhost:5432/
db_driver_dir: jars/postgresql-42.2.10.jar       # ex: /<path_of_cloned_directory/cQube/development/nifi/jars/postgresql-42.2.10.jar
nifi_port: 8096
