---
- name: Creating the Base Directory for the installation
  file:
    path: "{{ base_dir }}/cqube"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: install

- name: Creating Postgres backup directory
  file:
    path: "{{ base_dir }}/cqube/postgres/backups"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [install, update]

- name: Creating conf directory
  file:
    path: "{{ base_dir }}/cqube/conf"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [install, update]

- name: Copying the config.yml file as base_config.yml
  copy:
    src: ../config.yml
    dest: "{{ base_dir }}/cqube/conf/base_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install

- name: Copying the aws_s3_config.yml.template
  copy:
    src: ../aws_s3_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "local"

- name: Copying the aws_s3_config.yml.template
  copy:
    src: ../aws_s3_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "azure"

- name: Copying the aws_s3_config.yml
  copy:
    src: ../aws_s3_config.yml
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "s3"
  
- name: Copying the local_storage_config.yml.template 
  copy:
    src: ../local_storage_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "s3"

- name: Copying the local_storage_config.yml.template
  copy:
    src: ../local_storage_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "azure"

- name: Copying the local_storage_config.yml
  copy:
    src: ../local_storage_config.yml
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "local"
  
- name: Copying the config.yml file as base_config.yml
  copy:
    src: ../config.yml
    dest: "{{ base_dir }}/cqube/conf/base_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update

- name: Copying the aws_s3_config.yml 
  copy:
    src: ../aws_s3_config.yml
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "s3"


- name: Copying the aws_s3_config.yml.template
  copy:
    src: ../aws_s3_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "local"

- name: Copying the aws_s3_config.yml.template
  copy:
    src: ../aws_s3_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/aws_s3_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "azure"


- name: Copying the local_storage_config.yml.template
  copy:
    src: ../local_storage_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "local"

- name: Copying the local_storage_config.yml
  copy:
    src: ../local_storage_config.yml
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "local"

- name: Copying the local_storage_config.yml.template
  copy:
    src: ../local_storage_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "s3"

- name: Copying the local_storage_config.yml.template
  copy:
    src: ../local_storage_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/local_storage_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "azure"

- name: Copying the azure_container_config.yml
  copy:
    src: ../azure_container_config.yml
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "azure"

- name: Copying the azure_container_config.yml.template
  copy:
    src: ../azure_container_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "local"

- name: Copying the azure_container_config.yml.template
  copy:
    src: ../azure_container_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: install
  when: storage_type == "s3"

- name: Copying the azure_container_config.yml
  copy:
    src: ../azure_container_config.yml
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "azure"

- name: Copying the azure_container_config.yml.template
  copy: 
    src: ../azure_container_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "local"

- name: Copying the azure_container_config.yml.template
  copy:
    src: ../azure_container_config.yml.template
    dest: "{{ base_dir }}/cqube/conf/azure_container_config.yml"
    mode: '0644'
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
  tags: update
  when: storage_type == "s3"

- name: Setting timezone to IST
  timezone:
    name: Asia/Kolkata
  tags: [install, update]

