---

dependencies: []

galaxy_info:
  description: Install Kong API Gateway.
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  categories:
    - api
