- name: creating s3 bucket
  s3_bucket:
    name: "{{ s3_input_bucket }}"
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    state: present
    region: ap-south-1
    versioning: yes
    tags:
       name: "{{ s3_input_bucket }}"

- name: creating s3 bucket
  s3_bucket:
    name: "{{ s3_output_bucket }}"
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    state: present
    region: ap-south-1
    versioning: yes
    tags:
       name: "{{ s3_output_bucket }}"

